/**:
  ros__parameters:
    lanelet2_map_projector_type: UTM   # Options: MGRS, UTM, local
    latitude: 48.26438180295144064758        # Latitude of map_origin, using in UTM
    longitude: 11.66895824956896454694          # Longitude of map_origin, using in UTM

    center_line_resolution: 5.0         # [m]
